# Numpy Array and Operations

#### Numpy is Numarical python.It is a powerful python library used for numarical computing , Methementical Operation Data Analysis
#### and working with mulidimensional array

In [71]:
import numpy as np

In [72]:
arr = np.array([10,20,30,40,50,60,])
print(arr)

[10 20 30 40 50 60]


#### 2D Array

In [73]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3D Array

In [75]:
arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr)


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


#### Special Array Creation

In [77]:
arr = np.zeros([3,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Ones

In [78]:
arr = np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Identity Matrix

In [80]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Range

In [81]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## indexing in Numpy

#### indexing  is used to access a specific element from an Array

#### 1D Array

In [82]:
arr = np.array([10,20,30,40,50,60,])
print(arr[1])

20


#### 2D Array

In [83]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][0])
print(arr[1][1])
print(arr[1][2])


1
5
6


#### 3D Array

In [87]:
arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr[0,1,1])
print(arr[0,0,1])
print(arr[0,0,0])

4
2
1


# Slicing in Numpy

Slicing Extracts Multiple element from a Array 

#### 1D Array

In [90]:
arr = np.array([10,20,30,40,50,60])
print(arr[1:4])
print(arr[:4])
print(arr[3:])

[20 30 40]
[10 20 30 40]
[40 50 60]


#### 2D Array

In [91]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0:2])
print(arr[0:2][1:3])


[[1 2 3]
 [4 5 6]]
[[4 5 6]]


#### 3D Array

#### syntax [Depth , Row , Column]
#### Depth > Layer Number
#### Row > Row number
#### Column > Column Number

In [94]:
arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr[0])
print(arr[0,1])
print(arr[0,0])
print(arr[0,0])
print(arr[0,0,0])
print(arr[0,:,:])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[3 4]
[1 2]
[1 2]
1
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
