## Numpy Operation in python with Jupyter nootbook

#### Import Numpy

In [1]:
import numpy as np

## Combining Array

#### 1. Horizontel Stack (hstack)

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.hstack([a,b])

print(result)

[1 2 3 4 5 6]


#### 2. Vertical stack

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.vstack([a,b])

print(result)

[[1 2 3]
 [4 5 6]]


## Splitting Array

In [7]:
arr = np.array([1,2,3,4,5,6])

result = np.split(arr,3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


## Search Function

#### Find Index

In [13]:
arr = np.array([10,20,30,40,50,60])
index = np.where(arr == 30)
print(index)

(array([2]),)


#### Search Sorted Position

In [15]:
arr = np.array([10,20,30,40,50,60,70,80])

position = np.searchsorted(arr , 34)

print(position)

3


#### sort Function

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80])

sort = np.sort(arr)

print(sort)

[10 20 30 40 50 60 70 80]


## Aggregating & Statistical Functions

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print ("Sum:",np.sum(arr))
print ("Mean:", np.mean(arr))
print("Median", np.median(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Sum: 55
Mean: 5.5
Median 5.5
Max: 10
Min: 1


## Filter Arrays (Boolean Indexing)

In [19]:
arr = np.array([10,20,30,40,50,60,70,80])

result = arr [arr > 45]

print(result)

[50 60 70 80]


#### Multiple Codition

In [20]:
arr = np.array([10,20,30,40,50,60,70,80])

result = arr[(arr > 10) &(arr < 70 )]

print(result)

[20 30 40 50 60]


#### Masking Array

In [21]:
arr = np.array([10,20,30,40,50,60,70,80])

mask = arr > 30

print(mask)

filtered = arr [mask]

print(filtered)


[False False False  True  True  True  True  True]
[40 50 60 70 80]


#### Reshaping Array
##### convert array dimantion without changing data 

#### 1D to 3D

In [22]:
arr = np.array([10,20,30,40,50,60,70,80])

result = arr.reshape(2,2,2)

print(result)



[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


#### 1D to 2D

In [25]:
arr = np.array([10,20,30,40,50,60,70,80])

result = arr.reshape(2,4)

print(result)

[[10 20 30 40]
 [50 60 70 80]]


#### 3D to 1D

In [28]:
arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])

result = arr.reshape(8)

print(result)

[1 2 3 4 5 6 7 8]


#### Array Brodcasting

In [29]:
a = np.array([[1],[2],[3]])
b = np.array ([10,20,30])

result = a + b 

print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
